FROM ubuntu

RUN apt-get update && apt-get install ruby ruby-dev make build-essential zlib1g-dev python nodejs vim -y

RUN gem install jekyll bundler

WORKDIR /webpage

COPY Gemfile ./

RUN bundle install

EXPOSE 4000
CMD ["bundle", "exec", "jekyll", "serve", "--watch", "--incremental", "--host=0.0.0.0"]
